// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL5cvNUGZfiZ_EcsDn4LFSa7-8kW0r9Tg',
    appId: '1:686412771367:web:d4d6887f98f4078f145e02',
    messagingSenderId: '686412771367',
    projectId: 'todo-ia-app',
    authDomain: 'todo-ia-app.firebaseapp.com',
    storageBucket: 'todo-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv1cwZvMk_fEADCLBZ7QCpCuGIEeeWmag',
    appId: '1:686412771367:android:20eed265eb1cb957145e02',
    messagingSenderId: '686412771367',
    projectId: 'todo-ia-app',
    storageBucket: 'todo-ia-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXBBsv_pw8a21WtKPjtBca-O23pBV5YPc',
    appId: '1:686412771367:ios:a330156fce01c1c4145e02',
    messagingSenderId: '686412771367',
    projectId: 'todo-ia-app',
    storageBucket: 'todo-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.todoIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXBBsv_pw8a21WtKPjtBca-O23pBV5YPc',
    appId: '1:686412771367:ios:a330156fce01c1c4145e02',
    messagingSenderId: '686412771367',
    projectId: 'todo-ia-app',
    storageBucket: 'todo-ia-app.firebasestorage.app',
    iosBundleId: 'com.example.todoIa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL5cvNUGZfiZ_EcsDn4LFSa7-8kW0r9Tg',
    appId: '1:686412771367:web:78d53bae88a8d874145e02',
    messagingSenderId: '686412771367',
    projectId: 'todo-ia-app',
    authDomain: 'todo-ia-app.firebaseapp.com',
    storageBucket: 'todo-ia-app.firebasestorage.app',
  );
}
